default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  primary:
    <<: *default
    database: app_development
    host: <%= ENV.fetch("PRIMARY_DB_HOST") { "postgres-primary" } %>
  replica_1:
    <<: *default
    database: app_development
    host: <%= ENV.fetch("REPLICA1_DB_HOST") { "postgres-replica1" } %>
    replica: true
  replica_2:
    <<: *default
    database: app_development
    host: <%= ENV.fetch("REPLICA2_DB_HOST") { "postgres-replica2" } %>
    replica: true

test:
  <<: *default
  database: app_test
  host: postgres-primary

production:
  primary:
    <<: *default
    database: app_production
    host: <%= ENV.fetch("PRIMARY_DB_HOST") { "postgres-primary" } %>
  replica_1:
    <<: *default
    database: app_production
    host: <%= ENV.fetch("REPLICA1_DB_HOST") { "postgres-replica1" } %>
    replica: true
  replica_2:
    <<: *default
    database: app_production
    host: <%= ENV.fetch("REPLICA2_DB_HOST") { "postgres-replica2" } %>
    replica: true
